name: getx_shablon
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  lottie: ^3.1.2
  gap: ^3.0.1
  cloud_firestore: ^5.0.2
  get_storage: ^2.1.1
  device_preview: ^1.2.0
  keyboard_dismisser: ^3.0.0
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.2.3
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/font/
    - assets/images/
    - assets/images/banner/
    - assets/lotties/
    - assets/locales/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
